### ISSUE TITLE
Handle multiple source directories

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/ursa_major#136]
## Is your feature request related to a problem? Please describe.
While Ursa Major is currently set up to handle POST requests from two different applications (Aurora posts to `/accessions` and Zorya posts to `/bags`), it is not currently possible to config two different source directories.

## Describe the solution you'd like
Allow for source directories to change depending on which endpoint is POSTed to.

**Comment by bonniegee** [comment]
@helrond I'm realizing I'm a bit stuck here; I know that if I'm hitting the AccessionViewSet I want the source directory to be x, and for the BagViewSet I want it to be y. Should some code be added to each of those views, to set some variable somewhere? Is there another approach?

**Comment by helrond** [comment]
Hmmm I'm looking at this a bit more and the views really don't come into it; it's really a question of the BagDiscovery class. 

I think there are two options:
- Add awareness of what source the bag is coming from in Ursa Major, and have BagDiscovery target different source directories based on that field.
- symlink Zorya's `dest` directory with Ursa Major's `src` directory. I believe that Ursa Major's `src` directory is already a symlink to Aurora's `delivery` directory, so you'd have to do a bit of research to figure out the best way to do that.

Regardless, it may be necessary to add a custom method for the post method in the BagViewSet, since we want to make sure that Bags are created with a particular process status. It may also be possible to accomplish that via default values in the model.

My preference would be for the second option because it doesn't introduce additional complexity into the application (and we'd have to replicate this pattern each time we added a new source). The only thing I'm (very mildly) concerned about is possible collision with UUIDs across multiple systems. I think this could easily be handled with some checks/error handling when files are moved to the destination directory.

**Comment by bonniegee** [comment]
@helrond Thank you! I've looked into symbolic links for multiple directories and it doesn't seem possible (I've only found solutions around symbolically linking each file, which I don't _think_ is ideal for this use case). Unless there's a workaround for this, I'm going to start pursuing the first option.

**Comment by helrond** [comment]
Hmm I just tried and was able to create a symlink from `/efs/aurora/delivery/` so I think it's possible.

**Comment by bonniegee** [comment]
This was resolved by symlinks so I'm closing this--
