### ISSUE TITLE
Origin field not saving correctly

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/ursa_major#141]
## Describe the bug
The bag origin field for every item in Ursa Major dev is "aurora", even though in several instances it should be "digitization". "Aurora" is the default for the origin field.

## To reproduce
Send a package to Ursa Major with an origin other than "aurora." 

## Expected behavior
The origin field for a Ursa Major SIP should match the origin field in the JSON data.

## Additional context
The data in Zorya is correct.

**Comment by bonniegee** [comment]
@helrond I'm having issues figuring out where to fix this; is this is a view or a routine?

**Comment by helrond** [comment]
I *think* the solution to this is to add the `origin` field to the BagSerializer.

Longer explanation:
- Bags coming from Zorya are hitting the BagViewSet (aka `/bags`) endpoint and the data there is being created from the POST data.
- *if* Zorya is sending the origin and *if* that data is in the POST request as expected, then it should be in the model instance. HOWEVER, because `origin` is not in the serializer fields, I believe that data is filtered out and the default value is being applied. Serializers kind of act like web forms in the sense that they validate data between the view and a model instance.
